### ISSUE TITLE
Inherited docs reappear or sub-subclasses

### ISSUE THREAD

**Issue by arthurevans** [jonchardy/typedoc-plugin-no-inherit#1]
First, thanks for sharing this plugin.

I'm seeing the following issue for my use case. Given the inheritance tree:

HTMLElement > CustomElementA > CustomElementB

I want to suppress inheritance of the HTMLElement docs, because HTMLElement has approximately a zillion members, and it makes the docs impossible to read. But I want CustomElementA's members to show up as inherited members on CustomElementB.

If I put `@noInheritDoc` on `CustomElementA`, it correctly suppresses the `HTMLElement` docs... But then they show up again on `CustomElementB`.

Not sure whether that affects your use case; and looking at the code, I don't see an obvious way to approach this issue.

**Comment by jonchardy** [comment]
Thanks for the report. I'll take a look when I get a chance.

**Comment by jonchardy** [comment]
I just updated the package to handle this case. If a class/interface is marked noInheritDoc, anyone that inherits from it will no longer inherit the docs that were excised. Let me know if v1.1 works as you'd expect.

**Comment by arthurevans** [comment]
Thanks! Sorry, I saw this over the break and forgot to loop back to it. Tested, looks like it does what we want. Thanks so much!

**Comment by David-Melo** [comment]
Hello, this issue is happening to me on 1.1.6. Similar to what was reported above. I have have a class that is extending from a React.Component

ReactComponent > CustomElementA > CustomElementB

I have  @noInheritDoc on CustomElementA and it works as expected, but in the Docs, on CustomElementB the React Methods are showing up.

**Comment by jonchardy** [comment]
@David-Melo I see. This was because Typedoc doesn't resolve types for external classes. It should be resolved in 1.1.8 as CustomElementB will look up to CustomElementA to see what, if any, members to hide. Note that static members may still show up as Typedoc is not properly flagging them as inherited (still an open issue).
